#!/usr/bin/env node

const program = require('commander');
const { exec } = require('child-process-promise');

program
    .arguments('<name>')
    .action(
        function(name) {
            console.log(
                'Creating release %s',
                name
            );

            console.log('* updating branch "base"');
            exec('git checkout base')
                .then(
                    (result) => {

                    }
                )
                .catch(
                    (err) => {
                        console.error('ERROR: ', err);
                    }
                )
            ;
            // exec('git pull base');
            //
            // console.log(
            //     '* creating branch "release/%s/base" from branch "base"',
            //     name
            // );
            //
            // exec('git checkout -b base/' + name + ' base');
        }
    )
;

program.parse(process.argv);
